// Original practice dialogues, not real conversations or a live third-party course.
export const LESSONS = [
  { title: '酒店办理入住', partner: 'Receptionist · 前台', lines: [
    ['Hi, I have a reservation under Xiao Yao.', '你好，我用肖瑶的名字预订了房间。'],
    ['Welcome! May I see your passport, please?', '欢迎！请出示一下您的护照，好吗？'],
    ['Here you are. Is breakfast included?', '给您。房费包含早餐吗？'],
    ['Yes. Breakfast is served from seven to ten.', '包含。早餐供应时间是七点到十点。'],
    ['Great. What time is check-out?', '好的。几点退房？'],
    ['Check-out is at noon. Here is your key card.', '中午十二点退房。这是您的房卡。'],
  ], words: [['reservation', 'n. 预订', 'under + 姓名：预订登记在某人名下。'], ['included', 'adj. 包含在内的', 'Is breakfast included? 早餐包含在费用里吗？'], ['check-out', 'n. 退房', 'check out 作动词时不加连字符。']], pattern: ['May I see your …, please?', '请让我看一下您的……，好吗？'] },
  { title: '机场办理值机', partner: 'Agent · 值机人员', lines: [
    ['Hello, I would like to check in for my flight.', '你好，我想办理航班值机。'],
    ['Of course. May I have your passport?', '当然。请出示您的护照。'],
    ['Here it is. Could I have an aisle seat?', '给您。我可以要一个靠过道的座位吗？'],
    ['Yes. Are you checking any bags?', '可以。您有行李需要托运吗？'],
    ['Just this suitcase. Is it within the weight limit?', '只有这个行李箱。它在重量限制以内吗？'],
    ['Yes. Here is your boarding pass.', '是的。这是您的登机牌。'],
  ], words: [['aisle seat', 'n. 靠过道座位', 'window seat 是靠窗座位。'], ['suitcase', 'n. 行李箱', '可数名词：one suitcase。'], ['boarding pass', 'n. 登机牌', '登机时出示的凭证，不等同于护照。']], pattern: ['Could I have …?', '我可以要……吗？'] },
  { title: '入境时说明行程', partner: 'Officer · 入境官员', lines: [
    ['Good afternoon. Here is my passport.', '下午好。这是我的护照。'],
    ['What is the purpose of your visit?', '您此次来访的目的是什么？'],
    ['I am here on vacation for seven days.', '我是来度假的，停留七天。'],
    ['Where will you be staying?', '您会住在哪里？'],
    ['At the Park Hotel. Here is my booking confirmation.', '住在公园酒店。这是我的预订确认单。'],
    ['Thank you. Enjoy your stay.', '谢谢。祝您旅途愉快。'],
  ], words: [['purpose', 'n. 目的', 'the purpose of your visit：来访目的。'], ['on vacation', 'phr. 在度假', '回答来访目的时按实际行程说明。'], ['confirmation', 'n. 确认凭证', 'booking confirmation：预订确认单。']], pattern: ['I am here … for … days.', '我来这里……，停留……天。'] },
  { title: '寻找托运行李', partner: 'Staff · 机场工作人员', lines: [
    ['Excuse me, where can I collect my luggage?', '打扰一下，我在哪里领取行李？'],
    ['Which flight were you on?', '您乘坐的是哪个航班？'],
    ['Flight AB123 from Shanghai.', '从上海出发的 AB123 航班。'],
    ['Your bags should be on carousel six.', '您的行李应该在六号转盘。'],
    ['Thank you. Is that downstairs?', '谢谢。是在楼下吗？'],
    ['Yes. Follow the baggage claim signs.', '是的。沿着行李领取处的指示牌走。'],
  ], words: [['luggage', 'n. 行李', '不可数名词，通常不加 s。'], ['carousel', 'n. 行李转盘', '机场语境下指输送行李的转盘。'], ['baggage claim', 'n. 行李领取处', '可在机场指示牌上看到。']], pattern: ['Where can I collect …?', '我在哪里可以领取……？'] },
  { title: '打车去酒店', partner: 'Driver · 司机', lines: [
    ['Could you take me to this hotel, please?', '请送我去这家酒店，好吗？'],
    ['Sure. Do you have the address?', '好的。您有地址吗？'],
    ['Yes, here it is. How long will it take?', '有，在这里。大概要多久？'],
    ['About thirty minutes, depending on traffic.', '大约三十分钟，具体看路况。'],
    ['Do you accept credit cards?', '您接受信用卡付款吗？'],
    ['Yes. Please fasten your seat belt.', '接受。请系好安全带。'],
  ], words: [['address', 'n. 地址', '出示文字地址通常更便于司机确认。'], ['depending on', 'phr. 取决于', 'depending on traffic：视路况而定。'], ['seat belt', 'n. 安全带', 'fasten your seat belt：系好安全带。']], pattern: ['How long will it take?', '这要花多长时间？'] },
  { title: '购买地铁票', partner: 'Staff · 车站工作人员', lines: [
    ['I would like a ticket to Central Station.', '我想买一张到中央车站的票。'],
    ['A single ticket or a day pass?', '单程票还是一日通票？'],
    ['A day pass, please. How much is it?', '请给我一日通票。多少钱？'],
    ['It is eight dollars.', '八美元。'],
    ['Which line should I take?', '我应该坐哪条线路？'],
    ['Take the blue line and get off at the fourth stop.', '坐蓝线，在第四站下车。'],
  ], words: [['single ticket', 'n. 单程票', '也可说 one-way ticket。'], ['day pass', 'n. 一日通票', '具体可用线路和时段要另外确认。'], ['get off', 'phr. 下车', 'get off at …：在……下车。']], pattern: ['Which … should I take?', '我应该乘坐哪……？'] },
  { title: '在街上问路', partner: 'Local · 当地人', lines: [
    ['Excuse me, how do I get to the museum?', '打扰一下，请问去博物馆怎么走？'],
    ['Go straight and turn left at the traffic lights.', '直走，到红绿灯那里左转。'],
    ['Is it within walking distance?', '走路能到吗？'],
    ['Yes, it is about a ten-minute walk.', '能，步行大约十分钟。'],
    ['Will it be on my right?', '它会在我的右手边吗？'],
    ['Yes, opposite the bank.', '对，在银行对面。'],
  ], words: [['go straight', 'phr. 直走', '也可说 go straight ahead。'], ['walking distance', 'n. 步行可达的距离', 'within walking distance：步行范围内。'], ['opposite', 'prep. 在……对面', 'opposite the bank：在银行对面。']], pattern: ['How do I get to …?', '去……怎么走？'] },
  { title: '餐厅点餐', partner: 'Server · 服务员', lines: [
    ['Could we have a table for two?', '请给我们安排一张两人桌，好吗？'],
    ['Certainly. Here are the menus.', '当然。这是菜单。'],
    ['What would you recommend?', '您推荐什么菜？'],
    ['The grilled fish is very popular.', '烤鱼很受欢迎。'],
    ['I will have that, with rice on the side.', '我要一份烤鱼，另配米饭。'],
    ['Of course. Would you like anything to drink?', '好的。您想喝点什么？'],
  ], words: [['recommend', 'v. 推荐', 'What would you recommend? 您推荐什么？'], ['grilled', 'adj. 烤制的', 'grilled fish：烤鱼。'], ['on the side', 'phr. 另放；另配', '常用于配菜或酱汁。']], pattern: ['I will have …', '我要点……'] },
  { title: '说明食物过敏', partner: 'Server · 服务员', lines: [
    ['I have a peanut allergy. Does this dish contain peanuts?', '我对花生过敏。这道菜含花生吗？'],
    ['I am not sure. I will check with the chef.', '我不确定。我去向厨师确认。'],
    ['Could you also check the sauce?', '也请帮我确认一下酱汁好吗？'],
    ['Yes. The sauce contains peanut oil.', '好的。酱汁里含有花生油。'],
    ['Then I will choose something else. Thank you for checking.', '那我选别的菜。谢谢您帮忙确认。'],
    ['You are welcome. Let us check another option.', '不客气。我们来确认另一道菜。'],
  ], words: [['allergy', 'n. 过敏', 'a peanut allergy：花生过敏。'], ['contain', 'v. 含有', 'Does it contain …? 它含有……吗？'], ['sauce', 'n. 酱汁', '点餐时也需确认酱汁和配料。']], pattern: ['I have a … allergy.', '我对……过敏。'] },
  { title: '咖啡店买饮料', partner: 'Barista · 咖啡师', lines: [
    ['Could I have a small latte, please?', '请给我一杯小杯拿铁。'],
    ['Hot or iced?', '热的还是冰的？'],
    ['Hot, with oat milk, please.', '热的，请用燕麦奶。'],
    ['For here or to go?', '在这里喝还是带走？'],
    ['To go. Could you make it without sugar?', '带走。可以不加糖吗？'],
    ['Of course. That will be five dollars.', '当然。一共五美元。'],
  ], words: [['oat milk', 'n. 燕麦奶', 'with oat milk：用燕麦奶制作。'], ['to go', 'phr. 打包带走', '英式表达也常用 takeaway。'], ['without', 'prep. 不加；没有', 'without sugar：不加糖。']], pattern: ['Could you make it without …?', '可以不加……来制作吗？'] },
  { title: '购买景点门票', partner: 'Clerk · 售票员', lines: [
    ['Two adult tickets, please.', '请给我两张成人票。'],
    ['Would you like to visit the special exhibition too?', '您也想参观特别展览吗？'],
    ['Is it included in the ticket price?', '门票价格包含特别展览吗？'],
    ['No, it costs five dollars extra.', '不包含，需要另付五美元。'],
    ['Just the regular tickets, then. What time do you close?', '那只要普通门票。你们几点闭馆？'],
    ['We close at six. Last entry is at five.', '六点闭馆，最晚五点入场。'],
  ], words: [['adult', 'n./adj. 成人；成人的', 'adult ticket：成人票。'], ['exhibition', 'n. 展览', 'special exhibition：特别展览。'], ['last entry', 'n. 最晚入场时间', '可能早于闭馆时间。']], pattern: ['Is … included in the price?', '价格里包含……吗？'] },
  { title: '租用语音导览', partner: 'Staff · 博物馆工作人员', lines: [
    ['Do you have an audio guide in English?', '你们有英语语音导览吗？'],
    ['Yes. It is available at this counter.', '有。可以在这个柜台领取。'],
    ['How much does it cost to rent one?', '租一个要多少钱？'],
    ['It is six dollars, with a refundable deposit.', '租金六美元，另需支付可退还的押金。'],
    ['Where should I return it?', '我应该在哪里归还？'],
    ['At the exit, before you leave.', '离开前在出口归还。'],
  ], words: [['audio guide', 'n. 语音导览设备', 'audio 指音频。'], ['refundable', 'adj. 可退还的', 'a refundable deposit：可退还的押金。'], ['return', 'v. 归还', 'return it：把它还回去。']], pattern: ['Where should I return …?', '我应该在哪里归还……？'] },
  { title: '购物时试穿', partner: 'Assistant · 店员', lines: [
    ['Do you have this jacket in a medium?', '这件夹克有中码吗？'],
    ['Yes. Would you like to try it on?', '有。您想试穿吗？'],
    ['Please. Where are the fitting rooms?', '想。试衣间在哪里？'],
    ['They are at the back of the store.', '在商店里面的后方。'],
    ['This one is a little tight. Could I try a larger size?', '这件有点紧。我能试大一码吗？'],
    ['Certainly. I will get a large for you.', '当然。我给您拿大码。'],
  ], words: [['medium', 'n./adj. 中码；中等的', '尺码常写作 M。'], ['try on', 'phr. 试穿', '代词放中间：try it on。'], ['tight', 'adj. 紧的', 'a little tight：有点紧。']], pattern: ['Do you have this in …?', '这个有……吗？'] },
  { title: '结账与索取收据', partner: 'Cashier · 收银员', lines: [
    ['Can I pay by card?', '可以刷卡付款吗？'],
    ['Yes. Please tap your card here.', '可以。请在这里轻触银行卡。'],
    ['Could you charge me in the local currency?', '可以按当地货币给我结算吗？'],
    ['Of course. Please check the amount on the screen.', '当然。请核对屏幕上的金额。'],
    ['The amount is correct. May I have a receipt?', '金额正确。可以给我收据吗？'],
    ['Certainly. Here you are.', '当然。给您。'],
  ], words: [['tap', 'v. 轻触', 'tap your card：轻触银行卡完成支付。'], ['local currency', 'n. 当地货币', 'currency 指货币。'], ['receipt', 'n. 收据', '付款后可用于报销或退换货。']], pattern: ['May I have a receipt?', '可以给我一张收据吗？'] },
  { title: '询问退换货', partner: 'Assistant · 店员', lines: [
    ['I bought this shirt yesterday. Could I exchange it?', '我昨天买了这件衬衫。可以换货吗？'],
    ['Do you have the receipt?', '您有收据吗？'],
    ['Yes. I would like a smaller size.', '有。我想换小一码。'],
    ['I am sorry, that size is sold out.', '抱歉，那个尺码卖完了。'],
    ['Would a refund be possible instead?', '那可以退款吗？'],
    ['Let me check our return policy for you.', '我来帮您确认一下退货规定。'],
  ], words: [['exchange', 'v. 换货；交换', 'exchange it for …：把它换成……。'], ['sold out', 'adj. 售罄的', '某个尺码或产品已卖完。'], ['refund', 'n. 退款', 'a refund：一笔退款。']], pattern: ['Would … be possible instead?', '那改为……可以吗？'] },
  { title: '询问酒店无线网络', partner: 'Receptionist · 前台', lines: [
    ['Could you help me connect to the Wi-Fi?', '可以帮我连接无线网络吗？'],
    ['Sure. Please select the network called Guest.', '当然。请选择名为 Guest 的网络。'],
    ['Does it require a password?', '需要密码吗？'],
    ['Yes. The password is printed on your key-card holder.', '需要。密码印在您的房卡套上。'],
    ['I am connected now. Thank you.', '现在连上了。谢谢。'],
    ['You are welcome. Please let us know if it disconnects.', '不客气。如果断线，请告诉我们。'],
  ], words: [['connect to', 'phr. 连接到', 'connect to the Wi-Fi：连接无线网络。'], ['network', 'n. 网络', '选择酒店告知的正确网络名称。'], ['password', 'n. 密码', 'Does it require a password? 需要密码吗？']], pattern: ['Could you help me …?', '您可以帮我……吗？'] },
  { title: '反馈客房问题', partner: 'Receptionist · 前台', lines: [
    ['The air conditioner in my room is not working.', '我房间里的空调不工作了。'],
    ['I am sorry about that. What is your room number?', '很抱歉。您的房间号是多少？'],
    ['Room 308. It is quite warm inside.', '308 房间。里面挺热的。'],
    ['We can send someone to check it right away.', '我们可以马上派人去检查。'],
    ['If it cannot be fixed, could I change rooms?', '如果修不好，我可以换房间吗？'],
    ['Yes, we will check which rooms are available.', '可以，我们会查看哪些房间可用。'],
  ], words: [['air conditioner', 'n. 空调', '也常简称 AC。'], ['right away', 'phr. 立刻；马上', '表示尽快处理。'], ['available', 'adj. 可用的；有空的', 'available rooms：可入住的空房。']], pattern: ['The … in my room is not working.', '我房间里的……不工作了。'] },
  { title: '申请延迟退房', partner: 'Receptionist · 前台', lines: [
    ['Would it be possible to check out a little later?', '可以晚一点退房吗？'],
    ['What time would you prefer?', '您希望几点退房？'],
    ['Around two, if possible. My flight is in the evening.', '如果可以的话，两点左右。我的航班在晚上。'],
    ['We can offer that for an additional twenty dollars.', '可以，需要另付二十美元。'],
    ['Thank you. I will keep the regular check-out time.', '谢谢。那我还是按正常时间退房。'],
    ['No problem. We can store your bags afterward.', '没问题。退房后我们可以帮您寄存行李。'],
  ], words: [['check out', 'phr. 退房', '动词短语；check-out 是名词。'], ['additional', 'adj. 额外的', 'an additional fee：额外费用。'], ['afterward', 'adv. 之后', '这里指退房之后。']], pattern: ['Would it be possible to …?', '可以……吗？'] },
  { title: '寄存行李', partner: 'Staff · 酒店工作人员', lines: [
    ['Could I leave my luggage here for a few hours?', '我可以把行李在这里寄存几个小时吗？'],
    ['Certainly. How many bags do you have?', '当然。您有几件行李？'],
    ['One suitcase and one backpack.', '一个行李箱和一个背包。'],
    ['Here are your luggage tags. Please keep them safe.', '这是您的行李牌。请妥善保管。'],
    ['I will collect them at five. Is there a storage fee?', '我五点来取。寄存收费吗？'],
    ['It is free for hotel guests.', '对住店客人免费。'],
  ], words: [['backpack', 'n. 双肩背包', '与 suitcase（行李箱）区分。'], ['luggage tag', 'n. 行李牌', '取回行李时可能需要出示。'], ['storage fee', 'n. 寄存费', 'fee 指某项服务的费用。']], pattern: ['Could I leave … here?', '我可以把……留在这里吗？'] },
  { title: '预订餐厅座位', partner: 'Host · 餐厅接待员', lines: [
    ['I would like to book a table for tomorrow evening.', '我想订明天晚上的座位。'],
    ['For how many people?', '请问几位？'],
    ['Two people, at seven thirty.', '两位，七点半。'],
    ['May I have your name and phone number?', '请留下您的姓名和电话号码。'],
    ['Xiao Yao. Could we have a quiet table?', '肖瑶。能安排一个安静点的位置吗？'],
    ['We will do our best. See you tomorrow.', '我们会尽量安排。明天见。'],
  ], words: [['book', 'v. 预订', 'book a table：预订餐位。'], ['quiet', 'adj. 安静的', 'a quiet table：较安静的位置。'], ['do our best', 'phr. 尽力', '表示尽量安排，不是保证。']], pattern: ['I would like to book …', '我想预订……'] },
  { title: '确认火车站台', partner: 'Staff · 车站工作人员', lines: [
    ['Excuse me, which platform is the train to York leaving from?', '打扰一下，去约克的火车从哪个站台发车？'],
    ['It is leaving from platform four.', '从四号站台发车。'],
    ['Does this train go directly to York?', '这趟火车直达约克吗？'],
    ['Yes. You do not need to change trains.', '是的。您不需要换乘。'],
    ['How soon should I board?', '我应该什么时候上车？'],
    ['Board now. It leaves in ten minutes.', '现在就上车吧。十分钟后发车。'],
  ], words: [['platform', 'n. 站台', 'platform four：四号站台。'], ['directly', 'adv. 直接地', '这里指直达，无需换乘。'], ['board', 'v. 上车；登机', 'board the train：上火车。']], pattern: ['Do I need to change …?', '我需要换乘……吗？'] },
  { title: '错过火车后改签', partner: 'Clerk · 票务人员', lines: [
    ['I missed my train. Can I use this ticket on the next one?', '我错过了火车。这张票可以坐下一班吗？'],
    ['Let me check the ticket conditions.', '我确认一下这张票的使用条款。'],
    ['Thank you. When is the next departure?', '谢谢。下一班几点发车？'],
    ['At three fifteen, but you will need to change your booking.', '三点十五分，但您需要更改预订。'],
    ['Is there a fee to do that?', '改签需要手续费吗？'],
    ['There may be a fare difference. I will check it for you.', '可能需要补票价差额。我帮您查一下。'],
  ], words: [['missed', 'v. 错过了', 'miss a train：错过火车。'], ['departure', 'n. 出发；发车', 'departure time：出发时间。'], ['fare difference', 'n. 票价差额', 'fare 常用于交通票价。']], pattern: ['Can I use this … on …?', '我能用这个……乘坐……吗？'] },
  { title: '机场转机问路', partner: 'Staff · 机场工作人员', lines: [
    ['I have a connecting flight. Where should I go?', '我有一个转机航班。我应该去哪里？'],
    ['May I see your boarding pass?', '可以看一下您的登机牌吗？'],
    ['Here you are. Do I need to go through security again?', '给您。我需要再过一次安检吗？'],
    ['Yes. Follow the transfer signs to terminal two.', '需要。沿着转机指示牌去二号航站楼。'],
    ['Will I need to collect my checked bag?', '我需要领取托运行李吗？'],
    ['Please confirm that with your airline at the transfer desk.', '请在转机服务台向您的航空公司确认。'],
  ], words: [['connecting flight', 'n. 衔接航班', '转机时要赶的下一段航班。'], ['security', 'n. 安检；安全', 'go through security：通过安检。'], ['terminal', 'n. 航站楼', 'terminal two：二号航站楼。']], pattern: ['Do I need to … again?', '我需要再……一次吗？'] },
  { title: '询问航班延误', partner: 'Agent · 航空公司工作人员', lines: [
    ['My flight is delayed. Is there a new departure time?', '我的航班延误了。有新的起飞时间吗？'],
    ['It is now expected to leave at eight.', '目前预计八点起飞。'],
    ['Will the gate stay the same?', '登机口还是原来的吗？'],
    ['Please check the screens for gate updates.', '请留意屏幕上的登机口更新。'],
    ['I may miss my connection. Could you help me?', '我可能赶不上转机航班。可以帮帮我吗？'],
    ['Yes. Let us look at your booking.', '可以。我们来查看您的预订。'],
  ], words: [['delayed', 'adj. 延误的', 'My flight is delayed. 我的航班延误了。'], ['expected', 'adj. 预计的', '预计时间可能继续变化。'], ['gate', 'n. 登机口', 'gate updates：登机口变更信息。']], pattern: ['Is there a new … time?', '有新的……时间吗？'] },
  { title: '租车确认费用', partner: 'Agent · 租车人员', lines: [
    ['I have a car rental reservation for three days.', '我预订了三天的租车服务。'],
    ['May I see your driving licence and booking confirmation?', '请出示您的驾驶证和预订确认单。'],
    ['Here they are. What is included in the price?', '给您。这个价格包括哪些项目？'],
    ['Let us go through the rental agreement together.', '我们一起看一下租赁协议。'],
    ['Are there any extra charges for another driver?', '增加一名驾驶员有额外费用吗？'],
    ['Yes. I will explain the fee before you sign.', '有。我会在您签字前说明费用。'],
  ], words: [['rental', 'n./adj. 租赁；租用的', 'car rental：汽车租赁。'], ['agreement', 'n. 协议', 'rental agreement：租赁协议。'], ['extra charges', 'n. 额外费用', '签署前可逐项询问。']], pattern: ['Are there any extra charges for …?', '……有额外费用吗？'] },
  { title: '加油站求助', partner: 'Attendant · 加油站工作人员', lines: [
    ['Excuse me, this is a rental car. Could you help me?', '打扰一下，这是一辆租来的车。可以帮我吗？'],
    ['Of course. Which type of fuel does it use?', '当然。它使用哪种燃料？'],
    ['The label says unleaded petrol.', '标签上写着无铅汽油。'],
    ['Then use this pump. Please switch off the engine first.', '那请用这个加油机。先关闭发动机。'],
    ['Do I pay before or after filling up?', '我是在加油前还是加完后付款？'],
    ['Pay at the counter before you start.', '开始加油前在柜台付款。'],
  ], words: [['fuel', 'n. 燃料', '先确认车辆要求的燃料种类。'], ['unleaded petrol', 'n. 无铅汽油', '美式英语常说 unleaded gas。'], ['fill up', 'phr. 加满油', 'filling up 是其动名词形式。']], pattern: ['Do I … before or after …?', '我是在……之前还是之后……？'] },
  { title: '在药店描述不适', partner: 'Pharmacist · 药剂师', lines: [
    ['Hello, I have a sore throat. Could I speak to a pharmacist?', '你好，我嗓子疼。可以咨询药剂师吗？'],
    ['I am the pharmacist. How long have you had it?', '我就是药剂师。您疼了多久？'],
    ['Since yesterday. I also take a daily prescription medicine.', '从昨天开始。我还在每天服用一种处方药。'],
    ['Do you have the name of that medicine?', '您知道那种药的名字吗？'],
    ['Yes, here is the package. Should I see a doctor?', '知道，这是药盒。我需要去看医生吗？'],
    ['Let us check your symptoms and medicine first.', '我们先确认一下您的症状和用药情况。'],
  ], words: [['sore throat', 'n. 咽喉疼痛', 'I have a sore throat. 我嗓子疼。'], ['prescription', 'n./adj. 处方；处方的', 'prescription medicine：处方药。'], ['symptoms', 'n. 症状', '描述不适时说明症状和持续时间。']], pattern: ['I have had … since …', '我从……开始有……'] },
  { title: '护照遗失后求助', partner: 'Officer · 警员', lines: [
    ['I cannot find my passport. I think I have lost it.', '我找不到护照了。我想我把它弄丢了。'],
    ['When did you last have it?', '您最后一次拿着它是什么时候？'],
    ['This morning, at the hotel. I have already checked there.', '今天早上在酒店。我已经回去找过了。'],
    ['Do you have a copy or a photo of it?', '您有护照复印件或照片吗？'],
    ['Yes. Could I get a report for my consulate?', '有。我可以拿一份报告交给领事馆吗？'],
    ['We can explain how to report the loss here.', '我们可以说明在这里如何办理遗失报案。'],
  ], words: [['lost', 'adj./v. 遗失的；弄丢了', 'I have lost it. 我把它弄丢了。'], ['copy', 'n. 副本；复印件', 'a copy of my passport：护照复印件。'], ['consulate', 'n. 领事馆', '使馆通常用 embassy 表达。']], pattern: ['I cannot find my …', '我找不到我的……了。'] },
  { title: '紧急情况下求助', partner: 'Staff · 工作人员', lines: [
    ['Please help! My friend has fallen and is hurt.', '请帮帮忙！我的朋友摔倒受伤了。'],
    ['Where is your friend?', '您的朋友在哪里？'],
    ['By the main entrance. Could you call an ambulance?', '在正门旁边。您能叫救护车吗？'],
    ['Yes. I will call emergency services now.', '可以。我现在联系急救服务。'],
    ['Thank you. I will stay with my friend.', '谢谢。我会留在朋友身边。'],
    ['Help is on the way. Follow the dispatcher’s instructions.', '救援人员正在赶来。请听从急救调度员的指示。'],
  ], words: [['ambulance', 'n. 救护车', 'call an ambulance：叫救护车。'], ['entrance', 'n. 入口', 'main entrance：正门；主入口。'], ['on the way', 'phr. 在路上', 'Help is on the way. 救援正在赶来。']], pattern: ['Could you call …?', '您能联系……吗？'] },
  { title: '和旅途中的新朋友聊天', partner: 'Traveller · 另一位旅客', lines: [
    ['Hi, is this seat taken?', '你好，这个座位有人坐吗？'],
    ['No, please sit down. Are you visiting too?', '没有，请坐。你也是来旅行的吗？'],
    ['Yes, it is my first time here. What have you enjoyed most?', '是的，这是我第一次来。你最喜欢这里的什么？'],
    ['The old town. It is lovely to explore on foot.', '老城区。步行逛逛很不错。'],
    ['That sounds great. Do you have any tips?', '听起来很棒。你有什么小建议吗？'],
    ['Go early in the morning, when it is less crowded.', '早上早点去，那时人比较少。'],
  ], words: [['taken', 'adj. 已被占用的', 'Is this seat taken? 这个座位有人坐吗？'], ['explore', 'v. 探索；游览', 'explore on foot：步行游览。'], ['crowded', 'adj. 拥挤的', 'less crowded：人比较少的。']], pattern: ['It is my first time …', '这是我第一次……'] },
];

export function lessonForDate(date, offset = 0) {
  const stamp = Date.parse(date + 'T00:00:00Z');
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(stamp) || new Date(stamp).toISOString().slice(0,10) !== date || !Number.isInteger(offset)) throw new Error('Invalid lesson date');
  const day = Math.floor((stamp - Date.parse('2026-09-20T00:00:00Z')) / 86400000) + offset;
  const index = ((day % LESSONS.length) + LESSONS.length) % LESSONS.length;
  return { ...LESSONS[index], number: index + 1, total: LESSONS.length, date, review: offset !== 0 };
}
